// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: v2/quirks.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Quirks_Sum_FullMethodName = "/quirks.v2.Quirks/Sum"
)

// QuirksClient is the client API for Quirks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Same service name as quirks.v1.Quirks but in different package
// Tests how kaja handles services with same name in different packages
type QuirksClient interface {
	// Sums two integers (unlike quirks.v1.Quirks.Sum which concatenates strings)
	Sum(ctx context.Context, in *SumIntsRequest, opts ...grpc.CallOption) (*SumIntsResponse, error)
}

type quirksClient struct {
	cc grpc.ClientConnInterface
}

func NewQuirksClient(cc grpc.ClientConnInterface) QuirksClient {
	return &quirksClient{cc}
}

func (c *quirksClient) Sum(ctx context.Context, in *SumIntsRequest, opts ...grpc.CallOption) (*SumIntsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SumIntsResponse)
	err := c.cc.Invoke(ctx, Quirks_Sum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuirksServer is the server API for Quirks service.
// All implementations must embed UnimplementedQuirksServer
// for forward compatibility.
//
// Same service name as quirks.v1.Quirks but in different package
// Tests how kaja handles services with same name in different packages
type QuirksServer interface {
	// Sums two integers (unlike quirks.v1.Quirks.Sum which concatenates strings)
	Sum(context.Context, *SumIntsRequest) (*SumIntsResponse, error)
	mustEmbedUnimplementedQuirksServer()
}

// UnimplementedQuirksServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuirksServer struct{}

func (UnimplementedQuirksServer) Sum(context.Context, *SumIntsRequest) (*SumIntsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedQuirksServer) mustEmbedUnimplementedQuirksServer() {}
func (UnimplementedQuirksServer) testEmbeddedByValue()                {}

// UnsafeQuirksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuirksServer will
// result in compilation errors.
type UnsafeQuirksServer interface {
	mustEmbedUnimplementedQuirksServer()
}

func RegisterQuirksServer(s grpc.ServiceRegistrar, srv QuirksServer) {
	// If the following call panics, it indicates UnimplementedQuirksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Quirks_ServiceDesc, srv)
}

func _Quirks_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumIntsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuirksServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Quirks_Sum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuirksServer).Sum(ctx, req.(*SumIntsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Quirks_ServiceDesc is the grpc.ServiceDesc for Quirks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Quirks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quirks.v2.Quirks",
	HandlerType: (*QuirksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _Quirks_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/quirks.proto",
}
