// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: seating.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Seating_GetSeatMap_FullMethodName   = "/seating.Seating/GetSeatMap"
	Seating_HoldSeats_FullMethodName    = "/seating.Seating/HoldSeats"
	Seating_ConfirmSeats_FullMethodName = "/seating.Seating/ConfirmSeats"
	Seating_ReleaseSeats_FullMethodName = "/seating.Seating/ReleaseSeats"
	Seating_WatchSeats_FullMethodName   = "/seating.Seating/WatchSeats"
	Seating_PickSeats_FullMethodName    = "/seating.Seating/PickSeats"
)

// SeatingClient is the client API for Seating service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Live seat inventory for The Kaja Theatre. Seat state is owned here;
// the boxoffice service places holds and sales through the same RPCs
// that are exposed publicly.
type SeatingClient interface {
	// Full snapshot of a performance's seat map.
	GetSeatMap(ctx context.Context, in *GetSeatMapRequest, opts ...grpc.CallOption) (*GetSeatMapResponse, error)
	// Place a hold on specific seats. Holds expire automatically.
	HoldSeats(ctx context.Context, in *HoldSeatsRequest, opts ...grpc.CallOption) (*HoldSeatsResponse, error)
	// Turn a hold into a sale.
	ConfirmSeats(ctx context.Context, in *ConfirmSeatsRequest, opts ...grpc.CallOption) (*ConfirmSeatsResponse, error)
	// Release a hold early, freeing its seats.
	ReleaseSeats(ctx context.Context, in *ReleaseSeatsRequest, opts ...grpc.CallOption) (*ReleaseSeatsResponse, error)
	// Server streaming: sends a snapshot, then every hold/sale/release
	// live until the client disconnects.
	WatchSeats(ctx context.Context, in *WatchSeatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SeatUpdate], error)
	// Bidirectional streaming: an interactive picking session. Stream
	// commands in (watch, hold, release, confirm) and receive everyone's
	// seat changes plus your own results back.
	PickSeats(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PickSeatsCommand, SeatUpdate], error)
}

type seatingClient struct {
	cc grpc.ClientConnInterface
}

func NewSeatingClient(cc grpc.ClientConnInterface) SeatingClient {
	return &seatingClient{cc}
}

func (c *seatingClient) GetSeatMap(ctx context.Context, in *GetSeatMapRequest, opts ...grpc.CallOption) (*GetSeatMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeatMapResponse)
	err := c.cc.Invoke(ctx, Seating_GetSeatMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatingClient) HoldSeats(ctx context.Context, in *HoldSeatsRequest, opts ...grpc.CallOption) (*HoldSeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HoldSeatsResponse)
	err := c.cc.Invoke(ctx, Seating_HoldSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatingClient) ConfirmSeats(ctx context.Context, in *ConfirmSeatsRequest, opts ...grpc.CallOption) (*ConfirmSeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmSeatsResponse)
	err := c.cc.Invoke(ctx, Seating_ConfirmSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatingClient) ReleaseSeats(ctx context.Context, in *ReleaseSeatsRequest, opts ...grpc.CallOption) (*ReleaseSeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSeatsResponse)
	err := c.cc.Invoke(ctx, Seating_ReleaseSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatingClient) WatchSeats(ctx context.Context, in *WatchSeatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SeatUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Seating_ServiceDesc.Streams[0], Seating_WatchSeats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchSeatsRequest, SeatUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Seating_WatchSeatsClient = grpc.ServerStreamingClient[SeatUpdate]

func (c *seatingClient) PickSeats(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PickSeatsCommand, SeatUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Seating_ServiceDesc.Streams[1], Seating_PickSeats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PickSeatsCommand, SeatUpdate]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Seating_PickSeatsClient = grpc.BidiStreamingClient[PickSeatsCommand, SeatUpdate]

// SeatingServer is the server API for Seating service.
// All implementations must embed UnimplementedSeatingServer
// for forward compatibility.
//
// Live seat inventory for The Kaja Theatre. Seat state is owned here;
// the boxoffice service places holds and sales through the same RPCs
// that are exposed publicly.
type SeatingServer interface {
	// Full snapshot of a performance's seat map.
	GetSeatMap(context.Context, *GetSeatMapRequest) (*GetSeatMapResponse, error)
	// Place a hold on specific seats. Holds expire automatically.
	HoldSeats(context.Context, *HoldSeatsRequest) (*HoldSeatsResponse, error)
	// Turn a hold into a sale.
	ConfirmSeats(context.Context, *ConfirmSeatsRequest) (*ConfirmSeatsResponse, error)
	// Release a hold early, freeing its seats.
	ReleaseSeats(context.Context, *ReleaseSeatsRequest) (*ReleaseSeatsResponse, error)
	// Server streaming: sends a snapshot, then every hold/sale/release
	// live until the client disconnects.
	WatchSeats(*WatchSeatsRequest, grpc.ServerStreamingServer[SeatUpdate]) error
	// Bidirectional streaming: an interactive picking session. Stream
	// commands in (watch, hold, release, confirm) and receive everyone's
	// seat changes plus your own results back.
	PickSeats(grpc.BidiStreamingServer[PickSeatsCommand, SeatUpdate]) error
	mustEmbedUnimplementedSeatingServer()
}

// UnimplementedSeatingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeatingServer struct{}

func (UnimplementedSeatingServer) GetSeatMap(context.Context, *GetSeatMapRequest) (*GetSeatMapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeatMap not implemented")
}
func (UnimplementedSeatingServer) HoldSeats(context.Context, *HoldSeatsRequest) (*HoldSeatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HoldSeats not implemented")
}
func (UnimplementedSeatingServer) ConfirmSeats(context.Context, *ConfirmSeatsRequest) (*ConfirmSeatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmSeats not implemented")
}
func (UnimplementedSeatingServer) ReleaseSeats(context.Context, *ReleaseSeatsRequest) (*ReleaseSeatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSeats not implemented")
}
func (UnimplementedSeatingServer) WatchSeats(*WatchSeatsRequest, grpc.ServerStreamingServer[SeatUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchSeats not implemented")
}
func (UnimplementedSeatingServer) PickSeats(grpc.BidiStreamingServer[PickSeatsCommand, SeatUpdate]) error {
	return status.Error(codes.Unimplemented, "method PickSeats not implemented")
}
func (UnimplementedSeatingServer) mustEmbedUnimplementedSeatingServer() {}
func (UnimplementedSeatingServer) testEmbeddedByValue()                 {}

// UnsafeSeatingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeatingServer will
// result in compilation errors.
type UnsafeSeatingServer interface {
	mustEmbedUnimplementedSeatingServer()
}

func RegisterSeatingServer(s grpc.ServiceRegistrar, srv SeatingServer) {
	// If the following call panics, it indicates UnimplementedSeatingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Seating_ServiceDesc, srv)
}

func _Seating_GetSeatMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeatMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatingServer).GetSeatMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seating_GetSeatMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatingServer).GetSeatMap(ctx, req.(*GetSeatMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seating_HoldSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatingServer).HoldSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seating_HoldSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatingServer).HoldSeats(ctx, req.(*HoldSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seating_ConfirmSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatingServer).ConfirmSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seating_ConfirmSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatingServer).ConfirmSeats(ctx, req.(*ConfirmSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seating_ReleaseSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatingServer).ReleaseSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seating_ReleaseSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatingServer).ReleaseSeats(ctx, req.(*ReleaseSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seating_WatchSeats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchSeatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SeatingServer).WatchSeats(m, &grpc.GenericServerStream[WatchSeatsRequest, SeatUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Seating_WatchSeatsServer = grpc.ServerStreamingServer[SeatUpdate]

func _Seating_PickSeats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SeatingServer).PickSeats(&grpc.GenericServerStream[PickSeatsCommand, SeatUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Seating_PickSeatsServer = grpc.BidiStreamingServer[PickSeatsCommand, SeatUpdate]

// Seating_ServiceDesc is the grpc.ServiceDesc for Seating service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Seating_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seating.Seating",
	HandlerType: (*SeatingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSeatMap",
			Handler:    _Seating_GetSeatMap_Handler,
		},
		{
			MethodName: "HoldSeats",
			Handler:    _Seating_HoldSeats_Handler,
		},
		{
			MethodName: "ConfirmSeats",
			Handler:    _Seating_ConfirmSeats_Handler,
		},
		{
			MethodName: "ReleaseSeats",
			Handler:    _Seating_ReleaseSeats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchSeats",
			Handler:       _Seating_WatchSeats_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PickSeats",
			Handler:       _Seating_PickSeats_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "seating.proto",
}
