// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: v1/quirks.proto

package v1

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ================
// Quirks Interface
// ================

// Test unusual things
type Quirks interface {
	MethodWithAReallyLongNameGmthggupcbmnphflnnvu(context.Context, *Void) (*Message, error)

	// Concatenates two strings
	Sum(context.Context, *SumStringsRequest) (*SumStringsResponse, error)

	// Server streaming: generates a sequence of numbers from 1 to count
	GenerateNumbers(context.Context, *GenerateRequest) (*GenerateResponse, error)

	// Client streaming: accumulates streamed numbers and returns the total
	AccumulateSum(context.Context, *AccumulateRequest) (*AccumulateResponse, error)

	// Bidirectional streaming: echoes messages back with a prefix
	Echo(context.Context, *EchoMessage) (*EchoMessage, error)
}

// ======================
// Quirks Protobuf Client
// ======================

type quirksProtobufClient struct {
	client      HTTPClient
	urls        [5]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewQuirksProtobufClient creates a Protobuf client that implements the Quirks interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewQuirksProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Quirks {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "quirks.v1", "Quirks")
	urls := [5]string{
		serviceURL + "MethodWithAReallyLongNameGmthggupcbmnphflnnvu",
		serviceURL + "Sum",
		serviceURL + "GenerateNumbers",
		serviceURL + "AccumulateSum",
		serviceURL + "Echo",
	}

	return &quirksProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *quirksProtobufClient) MethodWithAReallyLongNameGmthggupcbmnphflnnvu(ctx context.Context, in *Void) (*Message, error) {
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks")
	ctx = ctxsetters.WithMethodName(ctx, "MethodWithAReallyLongNameGmthggupcbmnphflnnvu")
	caller := c.callMethodWithAReallyLongNameGmthggupcbmnphflnnvu
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *Void) (*Message, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*Void)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*Void) when calling interceptor")
					}
					return c.callMethodWithAReallyLongNameGmthggupcbmnphflnnvu(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Message)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Message) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *quirksProtobufClient) callMethodWithAReallyLongNameGmthggupcbmnphflnnvu(ctx context.Context, in *Void) (*Message, error) {
	out := new(Message)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *quirksProtobufClient) Sum(ctx context.Context, in *SumStringsRequest) (*SumStringsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks")
	ctx = ctxsetters.WithMethodName(ctx, "Sum")
	caller := c.callSum
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SumStringsRequest) (*SumStringsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SumStringsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SumStringsRequest) when calling interceptor")
					}
					return c.callSum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SumStringsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SumStringsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *quirksProtobufClient) callSum(ctx context.Context, in *SumStringsRequest) (*SumStringsResponse, error) {
	out := new(SumStringsResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *quirksProtobufClient) GenerateNumbers(ctx context.Context, in *GenerateRequest) (*GenerateResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks")
	ctx = ctxsetters.WithMethodName(ctx, "GenerateNumbers")
	caller := c.callGenerateNumbers
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GenerateRequest) (*GenerateResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GenerateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GenerateRequest) when calling interceptor")
					}
					return c.callGenerateNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GenerateResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GenerateResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *quirksProtobufClient) callGenerateNumbers(ctx context.Context, in *GenerateRequest) (*GenerateResponse, error) {
	out := new(GenerateResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *quirksProtobufClient) AccumulateSum(ctx context.Context, in *AccumulateRequest) (*AccumulateResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks")
	ctx = ctxsetters.WithMethodName(ctx, "AccumulateSum")
	caller := c.callAccumulateSum
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *AccumulateRequest) (*AccumulateResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*AccumulateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*AccumulateRequest) when calling interceptor")
					}
					return c.callAccumulateSum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AccumulateResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AccumulateResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *quirksProtobufClient) callAccumulateSum(ctx context.Context, in *AccumulateRequest) (*AccumulateResponse, error) {
	out := new(AccumulateResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *quirksProtobufClient) Echo(ctx context.Context, in *EchoMessage) (*EchoMessage, error) {
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks")
	ctx = ctxsetters.WithMethodName(ctx, "Echo")
	caller := c.callEcho
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *EchoMessage) (*EchoMessage, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EchoMessage)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EchoMessage) when calling interceptor")
					}
					return c.callEcho(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EchoMessage)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EchoMessage) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *quirksProtobufClient) callEcho(ctx context.Context, in *EchoMessage) (*EchoMessage, error) {
	out := new(EchoMessage)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ==================
// Quirks JSON Client
// ==================

type quirksJSONClient struct {
	client      HTTPClient
	urls        [5]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewQuirksJSONClient creates a JSON client that implements the Quirks interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewQuirksJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Quirks {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "quirks.v1", "Quirks")
	urls := [5]string{
		serviceURL + "MethodWithAReallyLongNameGmthggupcbmnphflnnvu",
		serviceURL + "Sum",
		serviceURL + "GenerateNumbers",
		serviceURL + "AccumulateSum",
		serviceURL + "Echo",
	}

	return &quirksJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *quirksJSONClient) MethodWithAReallyLongNameGmthggupcbmnphflnnvu(ctx context.Context, in *Void) (*Message, error) {
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks")
	ctx = ctxsetters.WithMethodName(ctx, "MethodWithAReallyLongNameGmthggupcbmnphflnnvu")
	caller := c.callMethodWithAReallyLongNameGmthggupcbmnphflnnvu
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *Void) (*Message, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*Void)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*Void) when calling interceptor")
					}
					return c.callMethodWithAReallyLongNameGmthggupcbmnphflnnvu(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Message)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Message) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *quirksJSONClient) callMethodWithAReallyLongNameGmthggupcbmnphflnnvu(ctx context.Context, in *Void) (*Message, error) {
	out := new(Message)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *quirksJSONClient) Sum(ctx context.Context, in *SumStringsRequest) (*SumStringsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks")
	ctx = ctxsetters.WithMethodName(ctx, "Sum")
	caller := c.callSum
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SumStringsRequest) (*SumStringsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SumStringsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SumStringsRequest) when calling interceptor")
					}
					return c.callSum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SumStringsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SumStringsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *quirksJSONClient) callSum(ctx context.Context, in *SumStringsRequest) (*SumStringsResponse, error) {
	out := new(SumStringsResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *quirksJSONClient) GenerateNumbers(ctx context.Context, in *GenerateRequest) (*GenerateResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks")
	ctx = ctxsetters.WithMethodName(ctx, "GenerateNumbers")
	caller := c.callGenerateNumbers
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GenerateRequest) (*GenerateResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GenerateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GenerateRequest) when calling interceptor")
					}
					return c.callGenerateNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GenerateResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GenerateResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *quirksJSONClient) callGenerateNumbers(ctx context.Context, in *GenerateRequest) (*GenerateResponse, error) {
	out := new(GenerateResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *quirksJSONClient) AccumulateSum(ctx context.Context, in *AccumulateRequest) (*AccumulateResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks")
	ctx = ctxsetters.WithMethodName(ctx, "AccumulateSum")
	caller := c.callAccumulateSum
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *AccumulateRequest) (*AccumulateResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*AccumulateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*AccumulateRequest) when calling interceptor")
					}
					return c.callAccumulateSum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AccumulateResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AccumulateResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *quirksJSONClient) callAccumulateSum(ctx context.Context, in *AccumulateRequest) (*AccumulateResponse, error) {
	out := new(AccumulateResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *quirksJSONClient) Echo(ctx context.Context, in *EchoMessage) (*EchoMessage, error) {
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks")
	ctx = ctxsetters.WithMethodName(ctx, "Echo")
	caller := c.callEcho
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *EchoMessage) (*EchoMessage, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EchoMessage)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EchoMessage) when calling interceptor")
					}
					return c.callEcho(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EchoMessage)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EchoMessage) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *quirksJSONClient) callEcho(ctx context.Context, in *EchoMessage) (*EchoMessage, error) {
	out := new(EchoMessage)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =====================
// Quirks Server Handler
// =====================

type quirksServer struct {
	Quirks
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewQuirksServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewQuirksServer(svc Quirks, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &quirksServer{
		Quirks:           svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *quirksServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *quirksServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// QuirksPathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const QuirksPathPrefix = "/twirp/quirks.v1.Quirks/"

func (s *quirksServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "quirks.v1.Quirks" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "MethodWithAReallyLongNameGmthggupcbmnphflnnvu":
		s.serveMethodWithAReallyLongNameGmthggupcbmnphflnnvu(ctx, resp, req)
		return
	case "Sum":
		s.serveSum(ctx, resp, req)
		return
	case "GenerateNumbers":
		s.serveGenerateNumbers(ctx, resp, req)
		return
	case "AccumulateSum":
		s.serveAccumulateSum(ctx, resp, req)
		return
	case "Echo":
		s.serveEcho(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *quirksServer) serveMethodWithAReallyLongNameGmthggupcbmnphflnnvu(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveMethodWithAReallyLongNameGmthggupcbmnphflnnvuJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveMethodWithAReallyLongNameGmthggupcbmnphflnnvuProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *quirksServer) serveMethodWithAReallyLongNameGmthggupcbmnphflnnvuJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "MethodWithAReallyLongNameGmthggupcbmnphflnnvu")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(Void)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Quirks.MethodWithAReallyLongNameGmthggupcbmnphflnnvu
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *Void) (*Message, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*Void)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*Void) when calling interceptor")
					}
					return s.Quirks.MethodWithAReallyLongNameGmthggupcbmnphflnnvu(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Message)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Message) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Message
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Message and nil error while calling MethodWithAReallyLongNameGmthggupcbmnphflnnvu. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quirksServer) serveMethodWithAReallyLongNameGmthggupcbmnphflnnvuProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "MethodWithAReallyLongNameGmthggupcbmnphflnnvu")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(Void)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Quirks.MethodWithAReallyLongNameGmthggupcbmnphflnnvu
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *Void) (*Message, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*Void)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*Void) when calling interceptor")
					}
					return s.Quirks.MethodWithAReallyLongNameGmthggupcbmnphflnnvu(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Message)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Message) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Message
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Message and nil error while calling MethodWithAReallyLongNameGmthggupcbmnphflnnvu. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quirksServer) serveSum(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveSumJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveSumProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *quirksServer) serveSumJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Sum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(SumStringsRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Quirks.Sum
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SumStringsRequest) (*SumStringsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SumStringsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SumStringsRequest) when calling interceptor")
					}
					return s.Quirks.Sum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SumStringsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SumStringsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SumStringsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SumStringsResponse and nil error while calling Sum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quirksServer) serveSumProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Sum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(SumStringsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Quirks.Sum
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SumStringsRequest) (*SumStringsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SumStringsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SumStringsRequest) when calling interceptor")
					}
					return s.Quirks.Sum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SumStringsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SumStringsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SumStringsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SumStringsResponse and nil error while calling Sum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quirksServer) serveGenerateNumbers(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGenerateNumbersJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGenerateNumbersProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *quirksServer) serveGenerateNumbersJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GenerateNumbers")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GenerateRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Quirks.GenerateNumbers
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GenerateRequest) (*GenerateResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GenerateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GenerateRequest) when calling interceptor")
					}
					return s.Quirks.GenerateNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GenerateResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GenerateResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GenerateResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GenerateResponse and nil error while calling GenerateNumbers. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quirksServer) serveGenerateNumbersProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GenerateNumbers")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GenerateRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Quirks.GenerateNumbers
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GenerateRequest) (*GenerateResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GenerateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GenerateRequest) when calling interceptor")
					}
					return s.Quirks.GenerateNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GenerateResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GenerateResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GenerateResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GenerateResponse and nil error while calling GenerateNumbers. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quirksServer) serveAccumulateSum(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveAccumulateSumJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveAccumulateSumProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *quirksServer) serveAccumulateSumJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "AccumulateSum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(AccumulateRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Quirks.AccumulateSum
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *AccumulateRequest) (*AccumulateResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*AccumulateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*AccumulateRequest) when calling interceptor")
					}
					return s.Quirks.AccumulateSum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AccumulateResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AccumulateResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *AccumulateResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AccumulateResponse and nil error while calling AccumulateSum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quirksServer) serveAccumulateSumProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "AccumulateSum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(AccumulateRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Quirks.AccumulateSum
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *AccumulateRequest) (*AccumulateResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*AccumulateRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*AccumulateRequest) when calling interceptor")
					}
					return s.Quirks.AccumulateSum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AccumulateResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AccumulateResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *AccumulateResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AccumulateResponse and nil error while calling AccumulateSum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quirksServer) serveEcho(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveEchoJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveEchoProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *quirksServer) serveEchoJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Echo")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(EchoMessage)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Quirks.Echo
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *EchoMessage) (*EchoMessage, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EchoMessage)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EchoMessage) when calling interceptor")
					}
					return s.Quirks.Echo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EchoMessage)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EchoMessage) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EchoMessage
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EchoMessage and nil error while calling Echo. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quirksServer) serveEchoProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Echo")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(EchoMessage)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Quirks.Echo
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *EchoMessage) (*EchoMessage, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EchoMessage)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EchoMessage) when calling interceptor")
					}
					return s.Quirks.Echo(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EchoMessage)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EchoMessage) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EchoMessage
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EchoMessage and nil error while calling Echo. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quirksServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *quirksServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *quirksServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "quirks.v1", "Quirks")
}

// ==================
// Quirks_2 Interface
// ==================

// Second service in the same file
type Quirks_2 interface {
	CamelCaseMethod(context.Context, *Void) (*Void, error)
}

// ========================
// Quirks_2 Protobuf Client
// ========================

type quirks_2ProtobufClient struct {
	client      HTTPClient
	urls        [1]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewQuirks_2ProtobufClient creates a Protobuf client that implements the Quirks_2 interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewQuirks_2ProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Quirks_2 {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	if literalURLs {
		serviceURL += baseServicePath(pathPrefix, "quirks.v1", "quirks_2")
	} else {
		serviceURL += baseServicePath(pathPrefix, "quirks.v1", "Quirks_2")
	}
	urls := [1]string{
		serviceURL + "CamelCaseMethod",
	}
	if literalURLs {
		urls = [1]string{
			serviceURL + "camelCaseMethod",
		}
	}

	return &quirks_2ProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *quirks_2ProtobufClient) CamelCaseMethod(ctx context.Context, in *Void) (*Void, error) {
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks_2")
	ctx = ctxsetters.WithMethodName(ctx, "CamelCaseMethod")
	caller := c.callCamelCaseMethod
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *Void) (*Void, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*Void)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*Void) when calling interceptor")
					}
					return c.callCamelCaseMethod(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Void)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Void) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *quirks_2ProtobufClient) callCamelCaseMethod(ctx context.Context, in *Void) (*Void, error) {
	out := new(Void)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ====================
// Quirks_2 JSON Client
// ====================

type quirks_2JSONClient struct {
	client      HTTPClient
	urls        [1]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewQuirks_2JSONClient creates a JSON client that implements the Quirks_2 interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewQuirks_2JSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Quirks_2 {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	if literalURLs {
		serviceURL += baseServicePath(pathPrefix, "quirks.v1", "quirks_2")
	} else {
		serviceURL += baseServicePath(pathPrefix, "quirks.v1", "Quirks_2")
	}
	urls := [1]string{
		serviceURL + "CamelCaseMethod",
	}
	if literalURLs {
		urls = [1]string{
			serviceURL + "camelCaseMethod",
		}
	}

	return &quirks_2JSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *quirks_2JSONClient) CamelCaseMethod(ctx context.Context, in *Void) (*Void, error) {
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks_2")
	ctx = ctxsetters.WithMethodName(ctx, "CamelCaseMethod")
	caller := c.callCamelCaseMethod
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *Void) (*Void, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*Void)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*Void) when calling interceptor")
					}
					return c.callCamelCaseMethod(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Void)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Void) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *quirks_2JSONClient) callCamelCaseMethod(ctx context.Context, in *Void) (*Void, error) {
	out := new(Void)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =======================
// Quirks_2 Server Handler
// =======================

type quirks_2Server struct {
	Quirks_2
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewQuirks_2Server builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewQuirks_2Server(svc Quirks_2, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &quirks_2Server{
		Quirks_2:         svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *quirks_2Server) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *quirks_2Server) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// Quirks_2PathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const Quirks_2PathPrefix = "/twirp/quirks.v1.Quirks_2/"

func (s *quirks_2Server) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "quirks.v1")
	ctx = ctxsetters.WithServiceName(ctx, "Quirks_2")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "quirks.v1.quirks_2" && pkgService != "quirks.v1.Quirks_2" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "camelCaseMethod", "CamelCaseMethod":
		s.serveCamelCaseMethod(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *quirks_2Server) serveCamelCaseMethod(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCamelCaseMethodJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCamelCaseMethodProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *quirks_2Server) serveCamelCaseMethodJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CamelCaseMethod")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(Void)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Quirks_2.CamelCaseMethod
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *Void) (*Void, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*Void)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*Void) when calling interceptor")
					}
					return s.Quirks_2.CamelCaseMethod(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Void)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Void) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Void
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Void and nil error while calling CamelCaseMethod. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quirks_2Server) serveCamelCaseMethodProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CamelCaseMethod")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(Void)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Quirks_2.CamelCaseMethod
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *Void) (*Void, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*Void)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*Void) when calling interceptor")
					}
					return s.Quirks_2.CamelCaseMethod(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Void)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Void) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Void
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Void and nil error while calling CamelCaseMethod. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *quirks_2Server) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 1
}

func (s *quirks_2Server) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *quirks_2Server) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "quirks.v1", "Quirks_2")
}

var twirpFileDescriptor1 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xb5, 0x85, 0x04, 0x32, 0x14, 0x85, 0xac, 0xa2, 0x2a, 0x32, 0x20, 0x21, 0x5f, 0x12,
	0x15, 0xb0, 0x9b, 0xf4, 0xc6, 0xad, 0x45, 0xa8, 0x1c, 0xda, 0x48, 0x24, 0x12, 0x48, 0x5c, 0xd0,
	0xda, 0x1d, 0xec, 0x15, 0xfb, 0xc7, 0xf5, 0xee, 0x5a, 0xe2, 0x5b, 0xf3, 0x11, 0x50, 0xbd, 0x36,
	0x36, 0x49, 0x73, 0xdb, 0x97, 0x79, 0xf3, 0x32, 0xf3, 0x1b, 0xc3, 0xb8, 0x5a, 0xc6, 0x77, 0x8e,
	0x97, 0xbf, 0x4c, 0x54, 0x94, 0xda, 0x6a, 0x3a, 0x6a, 0x54, 0xb5, 0x0c, 0xa6, 0xd5, 0x32, 0x16,
	0x3c, 0x89, 0x25, 0x1a, 0xc3, 0x32, 0xf4, 0x86, 0x30, 0x86, 0xc9, 0xd6, 0xc9, 0xad, 0x2d, 0xb9,
	0xca, 0xcc, 0x06, 0xef, 0x1c, 0x1a, 0x4b, 0x8f, 0x81, 0xb0, 0x19, 0x79, 0x43, 0x16, 0xa3, 0x0d,
	0x61, 0xf7, 0x2a, 0x99, 0x1d, 0x79, 0x95, 0x84, 0xef, 0x80, 0xf6, 0x1b, 0x4c, 0xa1, 0x95, 0x41,
	0x7a, 0x02, 0xc3, 0x12, 0x8d, 0x13, 0xb6, 0x69, 0x6b, 0x54, 0x38, 0x87, 0xf1, 0x15, 0x2a, 0x2c,
	0x99, 0xc5, 0x36, 0x7c, 0x0a, 0x83, 0x54, 0x3b, 0xe5, 0x9d, 0x83, 0x8d, 0x17, 0xe1, 0x29, 0xbc,
	0xe8, 0x8c, 0x5d, 0xa8, 0x72, 0x32, 0xc1, 0xb2, 0xb1, 0x36, 0x2a, 0x7c, 0x0b, 0x93, 0x8b, 0x34,
	0x75, 0xd2, 0x89, 0x5e, 0xec, 0x21, 0xf3, 0x29, 0xd0, 0xbe, 0xb9, 0x89, 0x9e, 0xc2, 0xc0, 0x6a,
	0xcb, 0x44, 0x3b, 0x44, 0x2d, 0xc2, 0x39, 0x3c, 0xfb, 0x94, 0xe6, 0xfa, 0xc6, 0x13, 0xa2, 0x33,
	0x78, 0x92, 0x6a, 0x65, 0x51, 0xb5, 0x5b, 0xb5, 0x72, 0xf5, 0xe7, 0x08, 0x86, 0x5f, 0x6a, 0xb2,
	0xf4, 0x33, 0xbc, 0xbf, 0x41, 0x9b, 0xeb, 0xdb, 0x6f, 0xdc, 0xe6, 0x17, 0x1b, 0x64, 0x42, 0xfc,
	0xbe, 0xd6, 0x2a, 0x5b, 0x33, 0x89, 0x57, 0xd2, 0xe6, 0x59, 0xe6, 0x8a, 0x34, 0x91, 0xaa, 0xc8,
	0x7f, 0x0a, 0xa5, 0x2a, 0x47, 0x47, 0x91, 0xe0, 0x49, 0xf4, 0x55, 0xf3, 0xdb, 0xe0, 0xb8, 0x7e,
	0xb6, 0x7f, 0x77, 0x09, 0x8f, 0xb6, 0x4e, 0xd2, 0x57, 0xd1, 0xbf, 0x9b, 0x45, 0x7b, 0xa7, 0x09,
	0x5e, 0x1f, 0xa8, 0x36, 0x7b, 0x5d, 0x77, 0xbc, 0xd7, 0xf5, 0xfe, 0x86, 0x06, 0xbd, 0x8e, 0x9d,
	0x5b, 0x04, 0x2f, 0x1f, 0xac, 0xf9, 0xac, 0x33, 0x42, 0xd7, 0xf0, 0xbc, 0x63, 0xb7, 0x3b, 0xdb,
	0xde, 0x09, 0xfe, 0x9b, 0x6d, 0x9f, 0xf9, 0x82, 0xd0, 0x0f, 0xf0, 0xf8, 0x9e, 0x2f, 0x3d, 0xe9,
	0x19, 0x7b, 0xc0, 0x83, 0x03, 0xbf, 0x2f, 0xc8, 0x19, 0x59, 0x9d, 0xc3, 0x53, 0x5f, 0xfc, 0xb1,
	0xa2, 0x73, 0x18, 0xa7, 0x4c, 0xa2, 0xf8, 0xc8, 0x0c, 0x7a, 0xf8, 0x7d, 0xaa, 0xdd, 0xf3, 0x72,
	0xf2, 0x7d, 0xcc, 0x95, 0xc5, 0x52, 0x31, 0x11, 0xb3, 0x82, 0xc7, 0xd5, 0x32, 0x19, 0xd6, 0xdf,
	0xfd, 0xf9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0x29, 0x78, 0xcd, 0x2b, 0x03, 0x00, 0x00,
}
