// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: v1/quirks.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SumStringsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             string                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumStringsRequest) Reset() {
	*x = SumStringsRequest{}
	mi := &file_v1_quirks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumStringsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumStringsRequest) ProtoMessage() {}

func (x *SumStringsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_quirks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumStringsRequest.ProtoReflect.Descriptor instead.
func (*SumStringsRequest) Descriptor() ([]byte, []int) {
	return file_v1_quirks_proto_rawDescGZIP(), []int{0}
}

func (x *SumStringsRequest) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *SumStringsRequest) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

type SumStringsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumStringsResponse) Reset() {
	*x = SumStringsResponse{}
	mi := &file_v1_quirks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumStringsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumStringsResponse) ProtoMessage() {}

func (x *SumStringsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_quirks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumStringsResponse.ProtoReflect.Descriptor instead.
func (*SumStringsResponse) Descriptor() ([]byte, []int) {
	return file_v1_quirks_proto_rawDescGZIP(), []int{1}
}

func (x *SumStringsResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_v1_quirks_proto protoreflect.FileDescriptor

const file_v1_quirks_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/quirks.proto\x12\tquirks.v1\x1a\x14v1/lib/message.proto\"/\n" +
	"\x11SumStringsRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\tR\x01b\",\n" +
	"\x12SumStringsResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\x96\x01\n" +
	"\x06Quirks\x12H\n" +
	"-MethodWithAReallyLongNameGmthggupcbmnphflnnvu\x12\t.lib.Void\x1a\f.lib.Message\x12B\n" +
	"\x03Sum\x12\x1c.quirks.v1.SumStringsRequest\x1a\x1d.quirks.v1.SumStringsResponse23\n" +
	"\bquirks_2\x12'\n" +
	"\x0fcamelCaseMethod\x12\t.lib.Void\x1a\t.lib.VoidB\x11Z\x0finternal/api/v1b\x06proto3"

var (
	file_v1_quirks_proto_rawDescOnce sync.Once
	file_v1_quirks_proto_rawDescData []byte
)

func file_v1_quirks_proto_rawDescGZIP() []byte {
	file_v1_quirks_proto_rawDescOnce.Do(func() {
		file_v1_quirks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_quirks_proto_rawDesc), len(file_v1_quirks_proto_rawDesc)))
	})
	return file_v1_quirks_proto_rawDescData
}

var file_v1_quirks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_quirks_proto_goTypes = []any{
	(*SumStringsRequest)(nil),  // 0: quirks.v1.SumStringsRequest
	(*SumStringsResponse)(nil), // 1: quirks.v1.SumStringsResponse
	(*Void)(nil),               // 2: lib.Void
	(*Message)(nil),            // 3: lib.Message
}
var file_v1_quirks_proto_depIdxs = []int32{
	2, // 0: quirks.v1.Quirks.MethodWithAReallyLongNameGmthggupcbmnphflnnvu:input_type -> lib.Void
	0, // 1: quirks.v1.Quirks.Sum:input_type -> quirks.v1.SumStringsRequest
	2, // 2: quirks.v1.quirks_2.camelCaseMethod:input_type -> lib.Void
	3, // 3: quirks.v1.Quirks.MethodWithAReallyLongNameGmthggupcbmnphflnnvu:output_type -> lib.Message
	1, // 4: quirks.v1.Quirks.Sum:output_type -> quirks.v1.SumStringsResponse
	2, // 5: quirks.v1.quirks_2.camelCaseMethod:output_type -> lib.Void
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_quirks_proto_init() }
func file_v1_quirks_proto_init() {
	if File_v1_quirks_proto != nil {
		return
	}
	file_v1_lib_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_quirks_proto_rawDesc), len(file_v1_quirks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_v1_quirks_proto_goTypes,
		DependencyIndexes: file_v1_quirks_proto_depIdxs,
		MessageInfos:      file_v1_quirks_proto_msgTypes,
	}.Build()
	File_v1_quirks_proto = out.File
	file_v1_quirks_proto_goTypes = nil
	file_v1_quirks_proto_depIdxs = nil
}
