#!/bin/bash
set -e
cd "$(dirname "$0")/.."

docker build -t kajatools/website-home:latest ./apps/home

kubectl apply -f apps/home/deployment.yaml
kubectl apply -f apps/home/service.yaml

kubectl get pods