#!/bin/bash
set -e
cd "$(dirname "$0")/.."

if [[ $(kubectl config current-context) != "kaja" ]]; then
    echo "Error: kubectl must be using kaja context"
    echo "Current context: $(kubectl config current-context)"
    exit 1
fi

# Get the first running pod with a volume mount and copy proto files
POD_NAME=$(kubectl get pods -l app=kaja --field-selector=status.phase=Running -o jsonpath='{.items[0].metadata.name}')
echo "Copying configuration and proto files to $POD_NAME"
kubectl exec $POD_NAME -- rm -rf /workspace/seating
kubectl exec $POD_NAME -- rm -rf /workspace/boxoffice
kubectl exec $POD_NAME -- mkdir /workspace/seating
kubectl exec $POD_NAME -- mkdir /workspace/boxoffice
kubectl cp apps/kaja/kaja.json $POD_NAME:/workspace/kaja.json
kubectl cp apps/seating/proto/seating.proto $POD_NAME:/workspace/seating/seating.proto
kubectl cp apps/boxoffice/proto/boxoffice.proto $POD_NAME:/workspace/boxoffice/boxoffice.proto

kubectl delete secret secrets
kubectl create secret generic secrets --from-literal=AI_API_KEY=$(cat .ai_api_key)

kubectl apply -k k8s/overlays/production
kubectl rollout restart deployment home-deployment
kubectl rollout restart deployment kaja-deployment
kubectl rollout restart deployment theatre-deployment
kubectl rollout restart deployment seating-deployment
kubectl rollout restart deployment boxoffice-deployment
kubectl rollout restart deployment grpc-quirks-deployment
kubectl rollout restart deployment twirp-quirks-deployment