#!/bin/bash
set -e

# Check if Go is installed, if not ask for user confirmation to install it using Homebrew
if ! command -v go &> /dev/null
then
    echo "Go is not installed."
    read -p "Would you like to install Go using Homebrew? (y/n) " -n 1 -r
    echo    # Move to a new line
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        echo "Installing Go using Homebrew..."
        brew install go
    else
        echo "Go installation skipped. Exiting script."
        exit 1
    fi
fi

# Check if protoc is installed, if not ask for user confirmation to install it using Homebrew
if ! command -v protoc &> /dev/null
then
    echo "protoc is not installed."
    read -p "Would you like to install protoc using Homebrew? (y/n) " -n 1 -r
    echo    # Move to a new line
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        echo "Installing protoc using Homebrew..."
        brew install protobuf
    else
        echo "protoc installation skipped. Exiting script."
        exit 1
    fi
fi

# Kill background apps when the script exits
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

cd "$(dirname "$0")/.."
export GOBIN=$PWD/build
export PATH=$GOBIN:$PATH
go install github.com/twitchtv/twirp/protoc-gen-twirp@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

cd "apps/users"
protoc --proto_path=. --plugin=protoc-gen-go=../../build/protoc-gen-go --go_out=. --plugin=protoc-gen-twirp=../../build/protoc-gen-twirp --twirp_out=. -Iproto/ $(find . -iname "*.proto")
# go build -o ../../build/users ./cmd/server/main.go
#../../build/users > users.log 2>&1 &

# Stop and remove the container if it already exists
docker rm -f kaja &> /dev/null || true

rm pipe &> /dev/null || true
mkfifo pipe

docker run --name kaja -a STDOUT -p 41520:41520 \
    -v $PWD/../users/proto:/workspace --pull=always \
    -e BASE_URL="http://host.docker.internal:41521" --add-host=host.docker.internal:host-gateway kajatools/kaja:latest > pipe &

while IFS= read -r line
do
  echo "$line"
  if [[ "$line" == *"Server started"* ]]; then
    break
  fi
done < pipe

rm pipe

# Open kaja in a default web browser
echo -e "${GREEN}Opening kaja URL http://localhost:41520/ in your default web browser${NC}"
python3 -m webbrowser http://localhost:41520/

#cd "../.."
go run cmd/server/main.go

#go run apps/home/cmd/server/main.go
