// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/oven.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Oven_GetOven_FullMethodName   = "/oven.Oven/GetOven"
	Oven_ClaimRack_FullMethodName = "/oven.Oven/ClaimRack"
	Oven_StartBake_FullMethodName = "/oven.Oven/StartBake"
	Oven_WatchOven_FullMethodName = "/oven.Oven/WatchOven"
)

// OvenClient is the client API for Oven service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Kaja Bakery's oven: four racks, one temperature, and other bakers.
//
// Baking is two calls: claim a rack, then start the bake. Cookie ids come from
// the bakebook catalog — start at https://bakebook.kaja.tools/cookies and copy
// any `id`.
//
// The oven runs on demo time: a minute in the recipe is a second in here, so a
// bake you start finishes while you are still looking at it.
//
// There are four racks and you are not the only baker. A rack you were about to
// claim can be gone by the time you claim it, and losing one to somebody faster
// is a normal thing to see here.
type OvenClient interface {
	// Every rack, what is on it and how long it has left, plus what is cooling
	// and what is already out on the counter. Takes no parameters.
	GetOven(ctx context.Context, in *GetOvenRequest, opts ...grpc.CallOption) (*GetOvenResponse, error)
	// Claim a free rack for a cookie and up to three trays. The rack is yours
	// for 45 seconds; a claim nobody bakes on is released automatically.
	ClaimRack(ctx context.Context, in *ClaimRackRequest, opts ...grpc.CallOption) (*ClaimRackResponse, error)
	// Bake it. This is the call that spends the dough and heats the oven, and
	// there is no unbaking a batch.
	StartBake(ctx context.Context, in *StartBakeRequest, opts ...grpc.CallOption) (*StartBakeResponse, error)
	// Streaming bonus: a snapshot of the oven, then every rack change in it,
	// live, until you disconnect. Needs a client that speaks gRPC streaming —
	// the kaja desktop app does; the web demo does not, so there it is fine to
	// just call GetOven again.
	WatchOven(ctx context.Context, in *WatchOvenRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OvenUpdate], error)
}

type ovenClient struct {
	cc grpc.ClientConnInterface
}

func NewOvenClient(cc grpc.ClientConnInterface) OvenClient {
	return &ovenClient{cc}
}

func (c *ovenClient) GetOven(ctx context.Context, in *GetOvenRequest, opts ...grpc.CallOption) (*GetOvenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOvenResponse)
	err := c.cc.Invoke(ctx, Oven_GetOven_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ovenClient) ClaimRack(ctx context.Context, in *ClaimRackRequest, opts ...grpc.CallOption) (*ClaimRackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimRackResponse)
	err := c.cc.Invoke(ctx, Oven_ClaimRack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ovenClient) StartBake(ctx context.Context, in *StartBakeRequest, opts ...grpc.CallOption) (*StartBakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartBakeResponse)
	err := c.cc.Invoke(ctx, Oven_StartBake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ovenClient) WatchOven(ctx context.Context, in *WatchOvenRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OvenUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Oven_ServiceDesc.Streams[0], Oven_WatchOven_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchOvenRequest, OvenUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Oven_WatchOvenClient = grpc.ServerStreamingClient[OvenUpdate]

// OvenServer is the server API for Oven service.
// All implementations must embed UnimplementedOvenServer
// for forward compatibility.
//
// The Kaja Bakery's oven: four racks, one temperature, and other bakers.
//
// Baking is two calls: claim a rack, then start the bake. Cookie ids come from
// the bakebook catalog — start at https://bakebook.kaja.tools/cookies and copy
// any `id`.
//
// The oven runs on demo time: a minute in the recipe is a second in here, so a
// bake you start finishes while you are still looking at it.
//
// There are four racks and you are not the only baker. A rack you were about to
// claim can be gone by the time you claim it, and losing one to somebody faster
// is a normal thing to see here.
type OvenServer interface {
	// Every rack, what is on it and how long it has left, plus what is cooling
	// and what is already out on the counter. Takes no parameters.
	GetOven(context.Context, *GetOvenRequest) (*GetOvenResponse, error)
	// Claim a free rack for a cookie and up to three trays. The rack is yours
	// for 45 seconds; a claim nobody bakes on is released automatically.
	ClaimRack(context.Context, *ClaimRackRequest) (*ClaimRackResponse, error)
	// Bake it. This is the call that spends the dough and heats the oven, and
	// there is no unbaking a batch.
	StartBake(context.Context, *StartBakeRequest) (*StartBakeResponse, error)
	// Streaming bonus: a snapshot of the oven, then every rack change in it,
	// live, until you disconnect. Needs a client that speaks gRPC streaming —
	// the kaja desktop app does; the web demo does not, so there it is fine to
	// just call GetOven again.
	WatchOven(*WatchOvenRequest, grpc.ServerStreamingServer[OvenUpdate]) error
	mustEmbedUnimplementedOvenServer()
}

// UnimplementedOvenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOvenServer struct{}

func (UnimplementedOvenServer) GetOven(context.Context, *GetOvenRequest) (*GetOvenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOven not implemented")
}
func (UnimplementedOvenServer) ClaimRack(context.Context, *ClaimRackRequest) (*ClaimRackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimRack not implemented")
}
func (UnimplementedOvenServer) StartBake(context.Context, *StartBakeRequest) (*StartBakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartBake not implemented")
}
func (UnimplementedOvenServer) WatchOven(*WatchOvenRequest, grpc.ServerStreamingServer[OvenUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchOven not implemented")
}
func (UnimplementedOvenServer) mustEmbedUnimplementedOvenServer() {}
func (UnimplementedOvenServer) testEmbeddedByValue()              {}

// UnsafeOvenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OvenServer will
// result in compilation errors.
type UnsafeOvenServer interface {
	mustEmbedUnimplementedOvenServer()
}

func RegisterOvenServer(s grpc.ServiceRegistrar, srv OvenServer) {
	// If the following call panics, it indicates UnimplementedOvenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Oven_ServiceDesc, srv)
}

func _Oven_GetOven_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOvenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OvenServer).GetOven(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oven_GetOven_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OvenServer).GetOven(ctx, req.(*GetOvenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oven_ClaimRack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OvenServer).ClaimRack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oven_ClaimRack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OvenServer).ClaimRack(ctx, req.(*ClaimRackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oven_StartBake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OvenServer).StartBake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oven_StartBake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OvenServer).StartBake(ctx, req.(*StartBakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oven_WatchOven_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchOvenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OvenServer).WatchOven(m, &grpc.GenericServerStream[WatchOvenRequest, OvenUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Oven_WatchOvenServer = grpc.ServerStreamingServer[OvenUpdate]

// Oven_ServiceDesc is the grpc.ServiceDesc for Oven service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Oven_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oven.Oven",
	HandlerType: (*OvenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOven",
			Handler:    _Oven_GetOven_Handler,
		},
		{
			MethodName: "ClaimRack",
			Handler:    _Oven_ClaimRack_Handler,
		},
		{
			MethodName: "StartBake",
			Handler:    _Oven_StartBake_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchOven",
			Handler:       _Oven_WatchOven_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/oven.proto",
}
