// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/oven.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RackState int32

const (
	RackState_RACK_STATE_UNKNOWN RackState = 0
	RackState_RACK_STATE_EMPTY   RackState = 1
	RackState_RACK_STATE_CLAIMED RackState = 2
	RackState_RACK_STATE_BAKING  RackState = 3
	RackState_RACK_STATE_COOLING RackState = 4
)

// Enum value maps for RackState.
var (
	RackState_name = map[int32]string{
		0: "RACK_STATE_UNKNOWN",
		1: "RACK_STATE_EMPTY",
		2: "RACK_STATE_CLAIMED",
		3: "RACK_STATE_BAKING",
		4: "RACK_STATE_COOLING",
	}
	RackState_value = map[string]int32{
		"RACK_STATE_UNKNOWN": 0,
		"RACK_STATE_EMPTY":   1,
		"RACK_STATE_CLAIMED": 2,
		"RACK_STATE_BAKING":  3,
		"RACK_STATE_COOLING": 4,
	}
)

func (x RackState) Enum() *RackState {
	p := new(RackState)
	*p = x
	return p
}

func (x RackState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RackState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_oven_proto_enumTypes[0].Descriptor()
}

func (RackState) Type() protoreflect.EnumType {
	return &file_proto_oven_proto_enumTypes[0]
}

func (x RackState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RackState.Descriptor instead.
func (RackState) EnumDescriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{0}
}

type ChangeReason int32

const (
	ChangeReason_CHANGE_REASON_UNKNOWN ChangeReason = 0
	ChangeReason_CHANGE_REASON_CLAIMED ChangeReason = 1
	ChangeReason_CHANGE_REASON_STARTED ChangeReason = 2
	// Out of the oven and onto the wire racks.
	ChangeReason_CHANGE_REASON_OUT ChangeReason = 3
	// Out of the oven and into the bin.
	ChangeReason_CHANGE_REASON_SCORCHED ChangeReason = 4
	// Cool enough to move to the counter.
	ChangeReason_CHANGE_REASON_COOLED   ChangeReason = 5
	ChangeReason_CHANGE_REASON_RELEASED ChangeReason = 6
	ChangeReason_CHANGE_REASON_EXPIRED  ChangeReason = 7
)

// Enum value maps for ChangeReason.
var (
	ChangeReason_name = map[int32]string{
		0: "CHANGE_REASON_UNKNOWN",
		1: "CHANGE_REASON_CLAIMED",
		2: "CHANGE_REASON_STARTED",
		3: "CHANGE_REASON_OUT",
		4: "CHANGE_REASON_SCORCHED",
		5: "CHANGE_REASON_COOLED",
		6: "CHANGE_REASON_RELEASED",
		7: "CHANGE_REASON_EXPIRED",
	}
	ChangeReason_value = map[string]int32{
		"CHANGE_REASON_UNKNOWN":  0,
		"CHANGE_REASON_CLAIMED":  1,
		"CHANGE_REASON_STARTED":  2,
		"CHANGE_REASON_OUT":      3,
		"CHANGE_REASON_SCORCHED": 4,
		"CHANGE_REASON_COOLED":   5,
		"CHANGE_REASON_RELEASED": 6,
		"CHANGE_REASON_EXPIRED":  7,
	}
)

func (x ChangeReason) Enum() *ChangeReason {
	p := new(ChangeReason)
	*p = x
	return p
}

func (x ChangeReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_oven_proto_enumTypes[1].Descriptor()
}

func (ChangeReason) Type() protoreflect.EnumType {
	return &file_proto_oven_proto_enumTypes[1]
}

func (x ChangeReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeReason.Descriptor instead.
func (ChangeReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{1}
}

type Rack struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Number int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	State  RackState              `protobuf:"varint,2,opt,name=state,proto3,enum=oven.RackState" json:"state,omitempty"`
	// All empty while the rack is.
	CookieId   string `protobuf:"bytes,3,opt,name=cookie_id,json=cookieId,proto3" json:"cookie_id,omitempty"`
	CookieName string `protobuf:"bytes,4,opt,name=cookie_name,json=cookieName,proto3" json:"cookie_name,omitempty"`
	Trays      int32  `protobuf:"varint,5,opt,name=trays,proto3" json:"trays,omitempty"`
	Cookies    int32  `protobuf:"varint,6,opt,name=cookies,proto3" json:"cookies,omitempty"`
	// Who has the rack. Everything you claim is "you"; the rest are the
	// bakery's own staff, who are here all day.
	Baker string `protobuf:"bytes,7,opt,name=baker,proto3" json:"baker,omitempty"`
	// When this state runs out: the claim expires, the bake finishes, the
	// batch is cool. Unset for an empty rack.
	Until         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rack) Reset() {
	*x = Rack{}
	mi := &file_proto_oven_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rack) ProtoMessage() {}

func (x *Rack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oven_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rack.ProtoReflect.Descriptor instead.
func (*Rack) Descriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{0}
}

func (x *Rack) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Rack) GetState() RackState {
	if x != nil {
		return x.State
	}
	return RackState_RACK_STATE_UNKNOWN
}

func (x *Rack) GetCookieId() string {
	if x != nil {
		return x.CookieId
	}
	return ""
}

func (x *Rack) GetCookieName() string {
	if x != nil {
		return x.CookieName
	}
	return ""
}

func (x *Rack) GetTrays() int32 {
	if x != nil {
		return x.Trays
	}
	return 0
}

func (x *Rack) GetCookies() int32 {
	if x != nil {
		return x.Cookies
	}
	return 0
}

func (x *Rack) GetBaker() string {
	if x != nil {
		return x.Baker
	}
	return ""
}

func (x *Rack) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type OvenState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the oven is set to right now. It follows whatever went in last.
	Celsius   int32   `protobuf:"varint,1,opt,name=celsius,proto3" json:"celsius,omitempty"`
	Racks     []*Rack `protobuf:"bytes,2,rep,name=racks,proto3" json:"racks,omitempty"`
	FreeRacks int32   `protobuf:"varint,3,opt,name=free_racks,json=freeRacks,proto3" json:"free_racks,omitempty"`
	// Cookies on the wire racks, and cookies already out for sale.
	Cooling       int32 `protobuf:"varint,4,opt,name=cooling,proto3" json:"cooling,omitempty"`
	OnCounter     int32 `protobuf:"varint,5,opt,name=on_counter,json=onCounter,proto3" json:"on_counter,omitempty"`
	BakedToday    int32 `protobuf:"varint,6,opt,name=baked_today,json=bakedToday,proto3" json:"baked_today,omitempty"`
	ScorchedToday int32 `protobuf:"varint,7,opt,name=scorched_today,json=scorchedToday,proto3" json:"scorched_today,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OvenState) Reset() {
	*x = OvenState{}
	mi := &file_proto_oven_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OvenState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OvenState) ProtoMessage() {}

func (x *OvenState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oven_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OvenState.ProtoReflect.Descriptor instead.
func (*OvenState) Descriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{1}
}

func (x *OvenState) GetCelsius() int32 {
	if x != nil {
		return x.Celsius
	}
	return 0
}

func (x *OvenState) GetRacks() []*Rack {
	if x != nil {
		return x.Racks
	}
	return nil
}

func (x *OvenState) GetFreeRacks() int32 {
	if x != nil {
		return x.FreeRacks
	}
	return 0
}

func (x *OvenState) GetCooling() int32 {
	if x != nil {
		return x.Cooling
	}
	return 0
}

func (x *OvenState) GetOnCounter() int32 {
	if x != nil {
		return x.OnCounter
	}
	return 0
}

func (x *OvenState) GetBakedToday() int32 {
	if x != nil {
		return x.BakedToday
	}
	return 0
}

func (x *OvenState) GetScorchedToday() int32 {
	if x != nil {
		return x.ScorchedToday
	}
	return 0
}

type Claim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RackNumber    int32                  `protobuf:"varint,2,opt,name=rack_number,json=rackNumber,proto3" json:"rack_number,omitempty"`
	CookieId      string                 `protobuf:"bytes,3,opt,name=cookie_id,json=cookieId,proto3" json:"cookie_id,omitempty"`
	Trays         int32                  `protobuf:"varint,4,opt,name=trays,proto3" json:"trays,omitempty"`
	Cookies       int32                  `protobuf:"varint,5,opt,name=cookies,proto3" json:"cookies,omitempty"`
	DoughGrams    int32                  `protobuf:"varint,6,opt,name=dough_grams,json=doughGrams,proto3" json:"dough_grams,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claim) Reset() {
	*x = Claim{}
	mi := &file_proto_oven_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim) ProtoMessage() {}

func (x *Claim) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oven_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim.ProtoReflect.Descriptor instead.
func (*Claim) Descriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{2}
}

func (x *Claim) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Claim) GetRackNumber() int32 {
	if x != nil {
		return x.RackNumber
	}
	return 0
}

func (x *Claim) GetCookieId() string {
	if x != nil {
		return x.CookieId
	}
	return ""
}

func (x *Claim) GetTrays() int32 {
	if x != nil {
		return x.Trays
	}
	return 0
}

func (x *Claim) GetCookies() int32 {
	if x != nil {
		return x.Cookies
	}
	return 0
}

func (x *Claim) GetDoughGrams() int32 {
	if x != nil {
		return x.DoughGrams
	}
	return 0
}

func (x *Claim) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type Batch struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RackNumber int32                  `protobuf:"varint,2,opt,name=rack_number,json=rackNumber,proto3" json:"rack_number,omitempty"`
	CookieId   string                 `protobuf:"bytes,3,opt,name=cookie_id,json=cookieId,proto3" json:"cookie_id,omitempty"`
	Cookies    int32                  `protobuf:"varint,4,opt,name=cookies,proto3" json:"cookies,omitempty"`
	Celsius    int32                  `protobuf:"varint,5,opt,name=celsius,proto3" json:"celsius,omitempty"`
	// How long this bake takes in demo seconds — the recipe's minutes.
	BakeSeconds   int32                  `protobuf:"varint,6,opt,name=bake_seconds,json=bakeSeconds,proto3" json:"bake_seconds,omitempty"`
	ReadyAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ready_at,json=readyAt,proto3" json:"ready_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_proto_oven_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oven_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{3}
}

func (x *Batch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Batch) GetRackNumber() int32 {
	if x != nil {
		return x.RackNumber
	}
	return 0
}

func (x *Batch) GetCookieId() string {
	if x != nil {
		return x.CookieId
	}
	return ""
}

func (x *Batch) GetCookies() int32 {
	if x != nil {
		return x.Cookies
	}
	return 0
}

func (x *Batch) GetCelsius() int32 {
	if x != nil {
		return x.Celsius
	}
	return 0
}

func (x *Batch) GetBakeSeconds() int32 {
	if x != nil {
		return x.BakeSeconds
	}
	return 0
}

func (x *Batch) GetReadyAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadyAt
	}
	return nil
}

type RackChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RackNumber    int32                  `protobuf:"varint,1,opt,name=rack_number,json=rackNumber,proto3" json:"rack_number,omitempty"`
	State         RackState              `protobuf:"varint,2,opt,name=state,proto3,enum=oven.RackState" json:"state,omitempty"`
	Reason        ChangeReason           `protobuf:"varint,3,opt,name=reason,proto3,enum=oven.ChangeReason" json:"reason,omitempty"`
	CookieId      string                 `protobuf:"bytes,4,opt,name=cookie_id,json=cookieId,proto3" json:"cookie_id,omitempty"`
	Baker         string                 `protobuf:"bytes,5,opt,name=baker,proto3" json:"baker,omitempty"`
	Cookies       int32                  `protobuf:"varint,6,opt,name=cookies,proto3" json:"cookies,omitempty"`
	ChangedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RackChange) Reset() {
	*x = RackChange{}
	mi := &file_proto_oven_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RackChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RackChange) ProtoMessage() {}

func (x *RackChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oven_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RackChange.ProtoReflect.Descriptor instead.
func (*RackChange) Descriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{4}
}

func (x *RackChange) GetRackNumber() int32 {
	if x != nil {
		return x.RackNumber
	}
	return 0
}

func (x *RackChange) GetState() RackState {
	if x != nil {
		return x.State
	}
	return RackState_RACK_STATE_UNKNOWN
}

func (x *RackChange) GetReason() ChangeReason {
	if x != nil {
		return x.Reason
	}
	return ChangeReason_CHANGE_REASON_UNKNOWN
}

func (x *RackChange) GetCookieId() string {
	if x != nil {
		return x.CookieId
	}
	return ""
}

func (x *RackChange) GetBaker() string {
	if x != nil {
		return x.Baker
	}
	return ""
}

func (x *RackChange) GetCookies() int32 {
	if x != nil {
		return x.Cookies
	}
	return 0
}

func (x *RackChange) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

type GetOvenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOvenRequest) Reset() {
	*x = GetOvenRequest{}
	mi := &file_proto_oven_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOvenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOvenRequest) ProtoMessage() {}

func (x *GetOvenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oven_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOvenRequest.ProtoReflect.Descriptor instead.
func (*GetOvenRequest) Descriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{5}
}

type GetOvenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oven          *OvenState             `protobuf:"bytes,1,opt,name=oven,proto3" json:"oven,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOvenResponse) Reset() {
	*x = GetOvenResponse{}
	mi := &file_proto_oven_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOvenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOvenResponse) ProtoMessage() {}

func (x *GetOvenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oven_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOvenResponse.ProtoReflect.Descriptor instead.
func (*GetOvenResponse) Descriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{6}
}

func (x *GetOvenResponse) GetOven() *OvenState {
	if x != nil {
		return x.Oven
	}
	return nil
}

type ClaimRackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An id from https://bakebook.kaja.tools/cookies, e.g. "brown-butter".
	CookieId string `protobuf:"bytes,1,opt,name=cookie_id,json=cookieId,proto3" json:"cookie_id,omitempty"`
	// 1 to 3. Defaults to 1.
	Trays         int32 `protobuf:"varint,2,opt,name=trays,proto3" json:"trays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRackRequest) Reset() {
	*x = ClaimRackRequest{}
	mi := &file_proto_oven_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRackRequest) ProtoMessage() {}

func (x *ClaimRackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oven_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRackRequest.ProtoReflect.Descriptor instead.
func (*ClaimRackRequest) Descriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimRackRequest) GetCookieId() string {
	if x != nil {
		return x.CookieId
	}
	return ""
}

func (x *ClaimRackRequest) GetTrays() int32 {
	if x != nil {
		return x.Trays
	}
	return 0
}

type ClaimRackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claim         *Claim                 `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRackResponse) Reset() {
	*x = ClaimRackResponse{}
	mi := &file_proto_oven_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRackResponse) ProtoMessage() {}

func (x *ClaimRackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oven_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRackResponse.ProtoReflect.Descriptor instead.
func (*ClaimRackResponse) Descriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimRackResponse) GetClaim() *Claim {
	if x != nil {
		return x.Claim
	}
	return nil
}

type StartBakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBakeRequest) Reset() {
	*x = StartBakeRequest{}
	mi := &file_proto_oven_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBakeRequest) ProtoMessage() {}

func (x *StartBakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oven_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBakeRequest.ProtoReflect.Descriptor instead.
func (*StartBakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{9}
}

func (x *StartBakeRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

type StartBakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         *Batch                 `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBakeResponse) Reset() {
	*x = StartBakeResponse{}
	mi := &file_proto_oven_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBakeResponse) ProtoMessage() {}

func (x *StartBakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oven_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBakeResponse.ProtoReflect.Descriptor instead.
func (*StartBakeResponse) Descriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{10}
}

func (x *StartBakeResponse) GetBatch() *Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

type WatchOvenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchOvenRequest) Reset() {
	*x = WatchOvenRequest{}
	mi := &file_proto_oven_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchOvenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchOvenRequest) ProtoMessage() {}

func (x *WatchOvenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oven_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchOvenRequest.ProtoReflect.Descriptor instead.
func (*WatchOvenRequest) Descriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{11}
}

// One frame of a WatchOven stream: the opening snapshot, then a change every
// time any rack in the oven changes state.
type OvenUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*OvenUpdate_Snapshot
	//	*OvenUpdate_Change
	Update        isOvenUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OvenUpdate) Reset() {
	*x = OvenUpdate{}
	mi := &file_proto_oven_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OvenUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OvenUpdate) ProtoMessage() {}

func (x *OvenUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oven_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OvenUpdate.ProtoReflect.Descriptor instead.
func (*OvenUpdate) Descriptor() ([]byte, []int) {
	return file_proto_oven_proto_rawDescGZIP(), []int{12}
}

func (x *OvenUpdate) GetUpdate() isOvenUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *OvenUpdate) GetSnapshot() *OvenState {
	if x != nil {
		if x, ok := x.Update.(*OvenUpdate_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *OvenUpdate) GetChange() *RackChange {
	if x != nil {
		if x, ok := x.Update.(*OvenUpdate_Change); ok {
			return x.Change
		}
	}
	return nil
}

type isOvenUpdate_Update interface {
	isOvenUpdate_Update()
}

type OvenUpdate_Snapshot struct {
	Snapshot *OvenState `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type OvenUpdate_Change struct {
	Change *RackChange `protobuf:"bytes,2,opt,name=change,proto3,oneof"`
}

func (*OvenUpdate_Snapshot) isOvenUpdate_Update() {}

func (*OvenUpdate_Change) isOvenUpdate_Update() {}

var File_proto_oven_proto protoreflect.FileDescriptor

const file_proto_oven_proto_rawDesc = "" +
	"\n" +
	"\x10proto/oven.proto\x12\x04oven\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x01\n" +
	"\x04Rack\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12%\n" +
	"\x05state\x18\x02 \x01(\x0e2\x0f.oven.RackStateR\x05state\x12\x1b\n" +
	"\tcookie_id\x18\x03 \x01(\tR\bcookieId\x12\x1f\n" +
	"\vcookie_name\x18\x04 \x01(\tR\n" +
	"cookieName\x12\x14\n" +
	"\x05trays\x18\x05 \x01(\x05R\x05trays\x12\x18\n" +
	"\acookies\x18\x06 \x01(\x05R\acookies\x12\x14\n" +
	"\x05baker\x18\a \x01(\tR\x05baker\x120\n" +
	"\x05until\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x05until\"\xe7\x01\n" +
	"\tOvenState\x12\x18\n" +
	"\acelsius\x18\x01 \x01(\x05R\acelsius\x12 \n" +
	"\x05racks\x18\x02 \x03(\v2\n" +
	".oven.RackR\x05racks\x12\x1d\n" +
	"\n" +
	"free_racks\x18\x03 \x01(\x05R\tfreeRacks\x12\x18\n" +
	"\acooling\x18\x04 \x01(\x05R\acooling\x12\x1d\n" +
	"\n" +
	"on_counter\x18\x05 \x01(\x05R\tonCounter\x12\x1f\n" +
	"\vbaked_today\x18\x06 \x01(\x05R\n" +
	"bakedToday\x12%\n" +
	"\x0escorched_today\x18\a \x01(\x05R\rscorchedToday\"\xe1\x01\n" +
	"\x05Claim\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vrack_number\x18\x02 \x01(\x05R\n" +
	"rackNumber\x12\x1b\n" +
	"\tcookie_id\x18\x03 \x01(\tR\bcookieId\x12\x14\n" +
	"\x05trays\x18\x04 \x01(\x05R\x05trays\x12\x18\n" +
	"\acookies\x18\x05 \x01(\x05R\acookies\x12\x1f\n" +
	"\vdough_grams\x18\x06 \x01(\x05R\n" +
	"doughGrams\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xe3\x01\n" +
	"\x05Batch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vrack_number\x18\x02 \x01(\x05R\n" +
	"rackNumber\x12\x1b\n" +
	"\tcookie_id\x18\x03 \x01(\tR\bcookieId\x12\x18\n" +
	"\acookies\x18\x04 \x01(\x05R\acookies\x12\x18\n" +
	"\acelsius\x18\x05 \x01(\x05R\acelsius\x12!\n" +
	"\fbake_seconds\x18\x06 \x01(\x05R\vbakeSeconds\x125\n" +
	"\bready_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\areadyAt\"\x88\x02\n" +
	"\n" +
	"RackChange\x12\x1f\n" +
	"\vrack_number\x18\x01 \x01(\x05R\n" +
	"rackNumber\x12%\n" +
	"\x05state\x18\x02 \x01(\x0e2\x0f.oven.RackStateR\x05state\x12*\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x12.oven.ChangeReasonR\x06reason\x12\x1b\n" +
	"\tcookie_id\x18\x04 \x01(\tR\bcookieId\x12\x14\n" +
	"\x05baker\x18\x05 \x01(\tR\x05baker\x12\x18\n" +
	"\acookies\x18\x06 \x01(\x05R\acookies\x129\n" +
	"\n" +
	"changed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\"\x10\n" +
	"\x0eGetOvenRequest\"6\n" +
	"\x0fGetOvenResponse\x12#\n" +
	"\x04oven\x18\x01 \x01(\v2\x0f.oven.OvenStateR\x04oven\"E\n" +
	"\x10ClaimRackRequest\x12\x1b\n" +
	"\tcookie_id\x18\x01 \x01(\tR\bcookieId\x12\x14\n" +
	"\x05trays\x18\x02 \x01(\x05R\x05trays\"6\n" +
	"\x11ClaimRackResponse\x12!\n" +
	"\x05claim\x18\x01 \x01(\v2\v.oven.ClaimR\x05claim\"-\n" +
	"\x10StartBakeRequest\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\"6\n" +
	"\x11StartBakeResponse\x12!\n" +
	"\x05batch\x18\x01 \x01(\v2\v.oven.BatchR\x05batch\"\x12\n" +
	"\x10WatchOvenRequest\"q\n" +
	"\n" +
	"OvenUpdate\x12-\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x0f.oven.OvenStateH\x00R\bsnapshot\x12*\n" +
	"\x06change\x18\x02 \x01(\v2\x10.oven.RackChangeH\x00R\x06changeB\b\n" +
	"\x06update*\x80\x01\n" +
	"\tRackState\x12\x16\n" +
	"\x12RACK_STATE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10RACK_STATE_EMPTY\x10\x01\x12\x16\n" +
	"\x12RACK_STATE_CLAIMED\x10\x02\x12\x15\n" +
	"\x11RACK_STATE_BAKING\x10\x03\x12\x16\n" +
	"\x12RACK_STATE_COOLING\x10\x04*\xe3\x01\n" +
	"\fChangeReason\x12\x19\n" +
	"\x15CHANGE_REASON_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15CHANGE_REASON_CLAIMED\x10\x01\x12\x19\n" +
	"\x15CHANGE_REASON_STARTED\x10\x02\x12\x15\n" +
	"\x11CHANGE_REASON_OUT\x10\x03\x12\x1a\n" +
	"\x16CHANGE_REASON_SCORCHED\x10\x04\x12\x18\n" +
	"\x14CHANGE_REASON_COOLED\x10\x05\x12\x1a\n" +
	"\x16CHANGE_REASON_RELEASED\x10\x06\x12\x19\n" +
	"\x15CHANGE_REASON_EXPIRED\x10\a2\xf3\x01\n" +
	"\x04Oven\x126\n" +
	"\aGetOven\x12\x14.oven.GetOvenRequest\x1a\x15.oven.GetOvenResponse\x12<\n" +
	"\tClaimRack\x12\x16.oven.ClaimRackRequest\x1a\x17.oven.ClaimRackResponse\x12<\n" +
	"\tStartBake\x12\x16.oven.StartBakeRequest\x1a\x17.oven.StartBakeResponse\x127\n" +
	"\tWatchOven\x12\x16.oven.WatchOvenRequest\x1a\x10.oven.OvenUpdate0\x01B\x0eZ\finternal/apib\x06proto3"

var (
	file_proto_oven_proto_rawDescOnce sync.Once
	file_proto_oven_proto_rawDescData []byte
)

func file_proto_oven_proto_rawDescGZIP() []byte {
	file_proto_oven_proto_rawDescOnce.Do(func() {
		file_proto_oven_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_oven_proto_rawDesc), len(file_proto_oven_proto_rawDesc)))
	})
	return file_proto_oven_proto_rawDescData
}

var file_proto_oven_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_oven_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_oven_proto_goTypes = []any{
	(RackState)(0),                // 0: oven.RackState
	(ChangeReason)(0),             // 1: oven.ChangeReason
	(*Rack)(nil),                  // 2: oven.Rack
	(*OvenState)(nil),             // 3: oven.OvenState
	(*Claim)(nil),                 // 4: oven.Claim
	(*Batch)(nil),                 // 5: oven.Batch
	(*RackChange)(nil),            // 6: oven.RackChange
	(*GetOvenRequest)(nil),        // 7: oven.GetOvenRequest
	(*GetOvenResponse)(nil),       // 8: oven.GetOvenResponse
	(*ClaimRackRequest)(nil),      // 9: oven.ClaimRackRequest
	(*ClaimRackResponse)(nil),     // 10: oven.ClaimRackResponse
	(*StartBakeRequest)(nil),      // 11: oven.StartBakeRequest
	(*StartBakeResponse)(nil),     // 12: oven.StartBakeResponse
	(*WatchOvenRequest)(nil),      // 13: oven.WatchOvenRequest
	(*OvenUpdate)(nil),            // 14: oven.OvenUpdate
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_proto_oven_proto_depIdxs = []int32{
	0,  // 0: oven.Rack.state:type_name -> oven.RackState
	15, // 1: oven.Rack.until:type_name -> google.protobuf.Timestamp
	2,  // 2: oven.OvenState.racks:type_name -> oven.Rack
	15, // 3: oven.Claim.expires_at:type_name -> google.protobuf.Timestamp
	15, // 4: oven.Batch.ready_at:type_name -> google.protobuf.Timestamp
	0,  // 5: oven.RackChange.state:type_name -> oven.RackState
	1,  // 6: oven.RackChange.reason:type_name -> oven.ChangeReason
	15, // 7: oven.RackChange.changed_at:type_name -> google.protobuf.Timestamp
	3,  // 8: oven.GetOvenResponse.oven:type_name -> oven.OvenState
	4,  // 9: oven.ClaimRackResponse.claim:type_name -> oven.Claim
	5,  // 10: oven.StartBakeResponse.batch:type_name -> oven.Batch
	3,  // 11: oven.OvenUpdate.snapshot:type_name -> oven.OvenState
	6,  // 12: oven.OvenUpdate.change:type_name -> oven.RackChange
	7,  // 13: oven.Oven.GetOven:input_type -> oven.GetOvenRequest
	9,  // 14: oven.Oven.ClaimRack:input_type -> oven.ClaimRackRequest
	11, // 15: oven.Oven.StartBake:input_type -> oven.StartBakeRequest
	13, // 16: oven.Oven.WatchOven:input_type -> oven.WatchOvenRequest
	8,  // 17: oven.Oven.GetOven:output_type -> oven.GetOvenResponse
	10, // 18: oven.Oven.ClaimRack:output_type -> oven.ClaimRackResponse
	12, // 19: oven.Oven.StartBake:output_type -> oven.StartBakeResponse
	14, // 20: oven.Oven.WatchOven:output_type -> oven.OvenUpdate
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_oven_proto_init() }
func file_proto_oven_proto_init() {
	if File_proto_oven_proto != nil {
		return
	}
	file_proto_oven_proto_msgTypes[12].OneofWrappers = []any{
		(*OvenUpdate_Snapshot)(nil),
		(*OvenUpdate_Change)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_oven_proto_rawDesc), len(file_proto_oven_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_oven_proto_goTypes,
		DependencyIndexes: file_proto_oven_proto_depIdxs,
		EnumInfos:         file_proto_oven_proto_enumTypes,
		MessageInfos:      file_proto_oven_proto_msgTypes,
	}.Build()
	File_proto_oven_proto = out.File
	file_proto_oven_proto_goTypes = nil
	file_proto_oven_proto_depIdxs = nil
}
