// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: boxoffice.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReservationStatus int32

const (
	ReservationStatus_RESERVATION_STATUS_UNKNOWN   ReservationStatus = 0
	ReservationStatus_RESERVATION_STATUS_PENDING   ReservationStatus = 1
	ReservationStatus_RESERVATION_STATUS_PURCHASED ReservationStatus = 2
	ReservationStatus_RESERVATION_STATUS_CANCELED  ReservationStatus = 3
	ReservationStatus_RESERVATION_STATUS_EXPIRED   ReservationStatus = 4
)

// Enum value maps for ReservationStatus.
var (
	ReservationStatus_name = map[int32]string{
		0: "RESERVATION_STATUS_UNKNOWN",
		1: "RESERVATION_STATUS_PENDING",
		2: "RESERVATION_STATUS_PURCHASED",
		3: "RESERVATION_STATUS_CANCELED",
		4: "RESERVATION_STATUS_EXPIRED",
	}
	ReservationStatus_value = map[string]int32{
		"RESERVATION_STATUS_UNKNOWN":   0,
		"RESERVATION_STATUS_PENDING":   1,
		"RESERVATION_STATUS_PURCHASED": 2,
		"RESERVATION_STATUS_CANCELED":  3,
		"RESERVATION_STATUS_EXPIRED":   4,
	}
)

func (x ReservationStatus) Enum() *ReservationStatus {
	p := new(ReservationStatus)
	*p = x
	return p
}

func (x ReservationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_boxoffice_proto_enumTypes[0].Descriptor()
}

func (ReservationStatus) Type() protoreflect.EnumType {
	return &file_boxoffice_proto_enumTypes[0]
}

func (x ReservationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationStatus.Descriptor instead.
func (ReservationStatus) EnumDescriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{0}
}

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PerformanceId string                 `protobuf:"bytes,2,opt,name=performance_id,json=performanceId,proto3" json:"performance_id,omitempty"`
	EventTitle    string                 `protobuf:"bytes,3,opt,name=event_title,json=eventTitle,proto3" json:"event_title,omitempty"`
	SeatIds       []string               `protobuf:"bytes,4,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	CustomerName  string                 `protobuf:"bytes,5,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	Status        ReservationStatus      `protobuf:"varint,6,opt,name=status,proto3,enum=boxoffice.ReservationStatus" json:"status,omitempty"`
	TotalCents    int32                  `protobuf:"varint,7,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_boxoffice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_boxoffice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{0}
}

func (x *Reservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reservation) GetPerformanceId() string {
	if x != nil {
		return x.PerformanceId
	}
	return ""
}

func (x *Reservation) GetEventTitle() string {
	if x != nil {
		return x.EventTitle
	}
	return ""
}

func (x *Reservation) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *Reservation) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *Reservation) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNKNOWN
}

func (x *Reservation) GetTotalCents() int32 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *Reservation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type Ticket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        string                 `protobuf:"bytes,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Section       string                 `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`
	PriceCents    int32                  `protobuf:"varint,3,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_boxoffice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_boxoffice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{1}
}

func (x *Ticket) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *Ticket) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Ticket) GetPriceCents() int32 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

type Order struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConfirmationCode string                 `protobuf:"bytes,1,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"` // "KAJA-7F3B"
	PerformanceId    string                 `protobuf:"bytes,2,opt,name=performance_id,json=performanceId,proto3" json:"performance_id,omitempty"`
	EventId          string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTitle       string                 `protobuf:"bytes,4,opt,name=event_title,json=eventTitle,proto3" json:"event_title,omitempty"`
	// Where to read more about the event in the theatre catalog API.
	EventUrl      string                 `protobuf:"bytes,5,opt,name=event_url,json=eventUrl,proto3" json:"event_url,omitempty"`
	CustomerName  string                 `protobuf:"bytes,6,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	Tickets       []*Ticket              `protobuf:"bytes,7,rep,name=tickets,proto3" json:"tickets,omitempty"`
	TotalCents    int32                  `protobuf:"varint,8,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	PurchasedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=purchased_at,json=purchasedAt,proto3" json:"purchased_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_boxoffice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_boxoffice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetConfirmationCode() string {
	if x != nil {
		return x.ConfirmationCode
	}
	return ""
}

func (x *Order) GetPerformanceId() string {
	if x != nil {
		return x.PerformanceId
	}
	return ""
}

func (x *Order) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Order) GetEventTitle() string {
	if x != nil {
		return x.EventTitle
	}
	return ""
}

func (x *Order) GetEventUrl() string {
	if x != nil {
		return x.EventUrl
	}
	return ""
}

func (x *Order) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *Order) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *Order) GetTotalCents() int32 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *Order) GetPurchasedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PurchasedAt
	}
	return nil
}

type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PerformanceId string                 `protobuf:"bytes,1,opt,name=performance_id,json=performanceId,proto3" json:"performance_id,omitempty"`
	SeatIds       []string               `protobuf:"bytes,2,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"` // max 6 seats per reservation
	CustomerName  string                 `protobuf:"bytes,3,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_boxoffice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxoffice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveRequest) GetPerformanceId() string {
	if x != nil {
		return x.PerformanceId
	}
	return ""
}

func (x *ReserveRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *ReserveRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

type ReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveResponse) Reset() {
	*x = ReserveResponse{}
	mi := &file_boxoffice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResponse) ProtoMessage() {}

func (x *ReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxoffice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResponse.ProtoReflect.Descriptor instead.
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveResponse) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type PurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	// Types that are valid to be assigned to Payment:
	//
	//	*PurchaseRequest_Card
	//	*PurchaseRequest_GiftCode
	Payment       isPurchaseRequest_Payment `protobuf_oneof:"payment"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseRequest) Reset() {
	*x = PurchaseRequest{}
	mi := &file_boxoffice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseRequest) ProtoMessage() {}

func (x *PurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxoffice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseRequest.ProtoReflect.Descriptor instead.
func (*PurchaseRequest) Descriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{5}
}

func (x *PurchaseRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *PurchaseRequest) GetPayment() isPurchaseRequest_Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *PurchaseRequest) GetCard() *Card {
	if x != nil {
		if x, ok := x.Payment.(*PurchaseRequest_Card); ok {
			return x.Card
		}
	}
	return nil
}

func (x *PurchaseRequest) GetGiftCode() *GiftCode {
	if x != nil {
		if x, ok := x.Payment.(*PurchaseRequest_GiftCode); ok {
			return x.GiftCode
		}
	}
	return nil
}

type isPurchaseRequest_Payment interface {
	isPurchaseRequest_Payment()
}

type PurchaseRequest_Card struct {
	Card *Card `protobuf:"bytes,2,opt,name=card,proto3,oneof"`
}

type PurchaseRequest_GiftCode struct {
	GiftCode *GiftCode `protobuf:"bytes,3,opt,name=gift_code,json=giftCode,proto3,oneof"`
}

func (*PurchaseRequest_Card) isPurchaseRequest_Payment() {}

func (*PurchaseRequest_GiftCode) isPurchaseRequest_Payment() {}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"` // demo: 4242424242424242
	Expiry        string                 `protobuf:"bytes,2,opt,name=expiry,proto3" json:"expiry,omitempty"` // MM/YY, any future date
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_boxoffice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_boxoffice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{6}
}

func (x *Card) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Card) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

type GiftCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // demo: "KAJA"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiftCode) Reset() {
	*x = GiftCode{}
	mi := &file_boxoffice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiftCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftCode) ProtoMessage() {}

func (x *GiftCode) ProtoReflect() protoreflect.Message {
	mi := &file_boxoffice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftCode.ProtoReflect.Descriptor instead.
func (*GiftCode) Descriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{7}
}

func (x *GiftCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseResponse) Reset() {
	*x = PurchaseResponse{}
	mi := &file_boxoffice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseResponse) ProtoMessage() {}

func (x *PurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxoffice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseResponse.ProtoReflect.Descriptor instead.
func (*PurchaseResponse) Descriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{8}
}

func (x *PurchaseResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_boxoffice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxoffice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{9}
}

func (x *CancelReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type CancelReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationResponse) Reset() {
	*x = CancelReservationResponse{}
	mi := &file_boxoffice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationResponse) ProtoMessage() {}

func (x *CancelReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxoffice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationResponse.ProtoReflect.Descriptor instead.
func (*CancelReservationResponse) Descriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{10}
}

type GetOrderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConfirmationCode string                 `protobuf:"bytes,1,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_boxoffice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxoffice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrderRequest) GetConfirmationCode() string {
	if x != nil {
		return x.ConfirmationCode
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_boxoffice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxoffice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_boxoffice_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_boxoffice_proto protoreflect.FileDescriptor

const file_boxoffice_proto_rawDesc = "" +
	"\n" +
	"\x0fboxoffice.proto\x12\tboxoffice\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x02\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eperformance_id\x18\x02 \x01(\tR\rperformanceId\x12\x1f\n" +
	"\vevent_title\x18\x03 \x01(\tR\n" +
	"eventTitle\x12\x19\n" +
	"\bseat_ids\x18\x04 \x03(\tR\aseatIds\x12#\n" +
	"\rcustomer_name\x18\x05 \x01(\tR\fcustomerName\x124\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1c.boxoffice.ReservationStatusR\x06status\x12\x1f\n" +
	"\vtotal_cents\x18\a \x01(\x05R\n" +
	"totalCents\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\\\n" +
	"\x06Ticket\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\tR\x06seatId\x12\x18\n" +
	"\asection\x18\x02 \x01(\tR\asection\x12\x1f\n" +
	"\vprice_cents\x18\x03 \x01(\x05R\n" +
	"priceCents\"\xe6\x02\n" +
	"\x05Order\x12+\n" +
	"\x11confirmation_code\x18\x01 \x01(\tR\x10confirmationCode\x12%\n" +
	"\x0eperformance_id\x18\x02 \x01(\tR\rperformanceId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1f\n" +
	"\vevent_title\x18\x04 \x01(\tR\n" +
	"eventTitle\x12\x1b\n" +
	"\tevent_url\x18\x05 \x01(\tR\beventUrl\x12#\n" +
	"\rcustomer_name\x18\x06 \x01(\tR\fcustomerName\x12+\n" +
	"\atickets\x18\a \x03(\v2\x11.boxoffice.TicketR\atickets\x12\x1f\n" +
	"\vtotal_cents\x18\b \x01(\x05R\n" +
	"totalCents\x12=\n" +
	"\fpurchased_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vpurchasedAt\"w\n" +
	"\x0eReserveRequest\x12%\n" +
	"\x0eperformance_id\x18\x01 \x01(\tR\rperformanceId\x12\x19\n" +
	"\bseat_ids\x18\x02 \x03(\tR\aseatIds\x12#\n" +
	"\rcustomer_name\x18\x03 \x01(\tR\fcustomerName\"K\n" +
	"\x0fReserveResponse\x128\n" +
	"\vreservation\x18\x01 \x01(\v2\x16.boxoffice.ReservationR\vreservation\"\x9e\x01\n" +
	"\x0fPurchaseRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12%\n" +
	"\x04card\x18\x02 \x01(\v2\x0f.boxoffice.CardH\x00R\x04card\x122\n" +
	"\tgift_code\x18\x03 \x01(\v2\x13.boxoffice.GiftCodeH\x00R\bgiftCodeB\t\n" +
	"\apayment\"6\n" +
	"\x04Card\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x16\n" +
	"\x06expiry\x18\x02 \x01(\tR\x06expiry\"\x1e\n" +
	"\bGiftCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\":\n" +
	"\x10PurchaseResponse\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.boxoffice.OrderR\x05order\"A\n" +
	"\x18CancelReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"\x1b\n" +
	"\x19CancelReservationResponse\">\n" +
	"\x0fGetOrderRequest\x12+\n" +
	"\x11confirmation_code\x18\x01 \x01(\tR\x10confirmationCode\":\n" +
	"\x10GetOrderResponse\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.boxoffice.OrderR\x05order*\xb6\x01\n" +
	"\x11ReservationStatus\x12\x1e\n" +
	"\x1aRESERVATION_STATUS_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aRESERVATION_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cRESERVATION_STATUS_PURCHASED\x10\x02\x12\x1f\n" +
	"\x1bRESERVATION_STATUS_CANCELED\x10\x03\x12\x1e\n" +
	"\x1aRESERVATION_STATUS_EXPIRED\x10\x042\xb7\x02\n" +
	"\tBoxOffice\x12@\n" +
	"\aReserve\x12\x19.boxoffice.ReserveRequest\x1a\x1a.boxoffice.ReserveResponse\x12C\n" +
	"\bPurchase\x12\x1a.boxoffice.PurchaseRequest\x1a\x1b.boxoffice.PurchaseResponse\x12^\n" +
	"\x11CancelReservation\x12#.boxoffice.CancelReservationRequest\x1a$.boxoffice.CancelReservationResponse\x12C\n" +
	"\bGetOrder\x12\x1a.boxoffice.GetOrderRequest\x1a\x1b.boxoffice.GetOrderResponseB\x0eZ\finternal/apib\x06proto3"

var (
	file_boxoffice_proto_rawDescOnce sync.Once
	file_boxoffice_proto_rawDescData []byte
)

func file_boxoffice_proto_rawDescGZIP() []byte {
	file_boxoffice_proto_rawDescOnce.Do(func() {
		file_boxoffice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boxoffice_proto_rawDesc), len(file_boxoffice_proto_rawDesc)))
	})
	return file_boxoffice_proto_rawDescData
}

var file_boxoffice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_boxoffice_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_boxoffice_proto_goTypes = []any{
	(ReservationStatus)(0),            // 0: boxoffice.ReservationStatus
	(*Reservation)(nil),               // 1: boxoffice.Reservation
	(*Ticket)(nil),                    // 2: boxoffice.Ticket
	(*Order)(nil),                     // 3: boxoffice.Order
	(*ReserveRequest)(nil),            // 4: boxoffice.ReserveRequest
	(*ReserveResponse)(nil),           // 5: boxoffice.ReserveResponse
	(*PurchaseRequest)(nil),           // 6: boxoffice.PurchaseRequest
	(*Card)(nil),                      // 7: boxoffice.Card
	(*GiftCode)(nil),                  // 8: boxoffice.GiftCode
	(*PurchaseResponse)(nil),          // 9: boxoffice.PurchaseResponse
	(*CancelReservationRequest)(nil),  // 10: boxoffice.CancelReservationRequest
	(*CancelReservationResponse)(nil), // 11: boxoffice.CancelReservationResponse
	(*GetOrderRequest)(nil),           // 12: boxoffice.GetOrderRequest
	(*GetOrderResponse)(nil),          // 13: boxoffice.GetOrderResponse
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
}
var file_boxoffice_proto_depIdxs = []int32{
	0,  // 0: boxoffice.Reservation.status:type_name -> boxoffice.ReservationStatus
	14, // 1: boxoffice.Reservation.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 2: boxoffice.Order.tickets:type_name -> boxoffice.Ticket
	14, // 3: boxoffice.Order.purchased_at:type_name -> google.protobuf.Timestamp
	1,  // 4: boxoffice.ReserveResponse.reservation:type_name -> boxoffice.Reservation
	7,  // 5: boxoffice.PurchaseRequest.card:type_name -> boxoffice.Card
	8,  // 6: boxoffice.PurchaseRequest.gift_code:type_name -> boxoffice.GiftCode
	3,  // 7: boxoffice.PurchaseResponse.order:type_name -> boxoffice.Order
	3,  // 8: boxoffice.GetOrderResponse.order:type_name -> boxoffice.Order
	4,  // 9: boxoffice.BoxOffice.Reserve:input_type -> boxoffice.ReserveRequest
	6,  // 10: boxoffice.BoxOffice.Purchase:input_type -> boxoffice.PurchaseRequest
	10, // 11: boxoffice.BoxOffice.CancelReservation:input_type -> boxoffice.CancelReservationRequest
	12, // 12: boxoffice.BoxOffice.GetOrder:input_type -> boxoffice.GetOrderRequest
	5,  // 13: boxoffice.BoxOffice.Reserve:output_type -> boxoffice.ReserveResponse
	9,  // 14: boxoffice.BoxOffice.Purchase:output_type -> boxoffice.PurchaseResponse
	11, // 15: boxoffice.BoxOffice.CancelReservation:output_type -> boxoffice.CancelReservationResponse
	13, // 16: boxoffice.BoxOffice.GetOrder:output_type -> boxoffice.GetOrderResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_boxoffice_proto_init() }
func file_boxoffice_proto_init() {
	if File_boxoffice_proto != nil {
		return
	}
	file_boxoffice_proto_msgTypes[5].OneofWrappers = []any{
		(*PurchaseRequest_Card)(nil),
		(*PurchaseRequest_GiftCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boxoffice_proto_rawDesc), len(file_boxoffice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boxoffice_proto_goTypes,
		DependencyIndexes: file_boxoffice_proto_depIdxs,
		EnumInfos:         file_boxoffice_proto_enumTypes,
		MessageInfos:      file_boxoffice_proto_msgTypes,
	}.Build()
	File_boxoffice_proto = out.File
	file_boxoffice_proto_goTypes = nil
	file_boxoffice_proto_depIdxs = nil
}
