apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxoffice-deployment
  labels:
    app: boxoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boxoffice
  template:
    metadata:
      labels:
        app: boxoffice
    spec:
      containers:
      - name: boxoffice
        image: kajatools/website-boxoffice:latest
        imagePullPolicy: Always
        env:
        - name: THEATRE_URL
          value: "http://theatre-service/theatre"
        - name: PUBLIC_THEATRE_URL
          value: "https://kaja.tools/theatre"
        - name: SEATING_ADDR
          value: "seating-service:80"
        ports:
        - containerPort: 41531
---
apiVersion: v1
kind: Service
metadata:
  name: boxoffice-service
spec:
  selector:
    app: boxoffice
  ports:
    - port: 80
      targetPort: 41531
  type: ClusterIP
