apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaja-deployment
  labels:
    app: kaja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaja
  template:
    metadata:
      labels:
        app: kaja
    spec:
      containers:
      - name: kaja
        image: kajatools/kaja:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: workspace-volume
          mountPath: /workspace
        env:
        - name: BASE_URL
          value: "http://users-service"
        - name: PATH_PREFIX
          value: "/demo"
        ports:
        - containerPort: 41520
      volumes:
      - name: workspace-volume
        persistentVolumeClaim:
          claimName: workspace-claim
---
apiVersion: v1
kind: Service
metadata:
  name: kaja-service
spec:
  selector:
    app: kaja
  ports:
    - port: 80
      targetPort: 41520
  type: ClusterIP