apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- boxoffice.yaml
- cluster-issuer.yaml
- grpc-quirks.yaml
- home.yaml
- ingress.yaml
- ingress-grpc.yaml
- kaja.yaml
- kaja-auto-update.yaml
- seating.yaml
- theatre.yaml
- twirp-quirks.yaml
- workspace-volume.yaml