apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: kajatools/website-users:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: workspace-volume
          mountPath: /workspace
        env:
        - name: DB_DIR
          value: "/workspace/users_db"
        ports:
        - containerPort: 41521
        resources:
          limits:
            cpu: "0.2"
            memory: "256Mi"
          requests:
            cpu: "0.1" 
            memory: "128Mi"
      volumes:
      - name: workspace-volume
        persistentVolumeClaim:
          claimName: workspace-claim
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
    - port: 80
      targetPort: 41521
  type: ClusterIP