name: main
on:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push website-home
        uses: docker/build-push-action@v3
        with:
          context: ./apps/home
          push: true
          tags: |
            kajatools/website-home:latest
      - name: Build and push website-teams
        uses: docker/build-push-action@v3
        with:
          context: ./apps/teams
          push: true
          tags: |
            kajatools/website-teams:latest
      - name: Build and push website-users
        uses: docker/build-push-action@v3
        with:
          context: ./apps/users
          push: true
          tags: |
            kajatools/website-users:latest
